version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nextauth
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nextauth"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: nextjs-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3123:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production

volumes:
  pgdata: